// Generated by CoffeeScript 1.7.1
var empty;

empty = {};

module.exports = function(dest) {
  if (!dest) {
    dest = {};
  }
  
	var i, l, source, name;
	for (i = 1, l = arguments.length; i < l; i += 1) {
		source = arguments[i];
		for (name in source) {
			if (!(name in dest) || (dest[name] !== source[name] && (!(name in empty) || empty[name] !== source[name]))) {
				dest[name] = source[name];
			}
		}
	}
	;
  return dest;
};
